########################
# Author: Mengjuei Hsieh
# License: Public Domain
########################

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install binutils-mingw-w64-x86-64
  - sudo apt-get install binutils-mingw-w64-i686
  - sudo apt-get install gcc-mingw-w64-x86-64
  - sudo apt-get install gcc-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64-x86-64
  - sudo apt-get install g++-mingw-w64-i686
  - sudo apt-get install gfortran-mingw-w64-x86-64
  - sudo apt-get install gfortran-mingw-w64-i686
  - sudo apt-get install mingw-w64
  - sudo apt-get install mingw-w64-dev
  - sudo apt-get install mingw-w64-tools
  - sudo apt-get install -qq -y wine
  - sudo apt-get install tree
  - sudo apt-get autoremove
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - mkdir -p $HOME/.wine/drive_c/windows
  - chmod -R 775 $HOME/.wine
script: true
