########################
# Author: Mengjuei Hsieh
# License: Public Domain
########################

language: cpp
os: linux
dist: trusty
group: beta
env: C_COMPILER=x86_64-w64-mingw32-gcc CXX_COMPILER=x86_64-w64-mingw32-g++ RC_COMPILER=x86_64-w64-mingw32-windres CROSS_COMPILE=yes
addons:
  apt:
    #sources:
    #  - ubuntu-toolchain-r-test
    packages:
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - g++-mingw-w64-x86-64
      - gfortran-mingw-w64-x86-64
      - mingw-w64
      - mingw-w64-x86-64-dev
      - mingw-w64-tools

before_install:
  - sudo dpkg --add-architecture i386
  - sudo add-apt-repository -y ppa:wine/wine-builds
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y wine
  - sudo apt-get install tree
  - sudo apt-get autoremove
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir -p $HOME/.wine/drive_c/windows
  - chmod -R 775 $HOME/.wine
  - rm -f $HOME/.wine/drive_c/windows/libstdc++-6.dll
  - rm -f $HOME/.wine/drive_c/windows/libgcc_s_sjlj-1.dll
  - rm -f $HOME/.wine/drive_c/windows/libgfortran-3.dll
  - rm -f $HOME/.wine/drive_c/windows/libquadmath-0.dll
  - ln -sfn /usr/lib/gcc/x86_64-w64-mingw32/4.6/libstdc++-6.dll     $HOME/.wine/drive_c/windows/
  - ln -sfn /usr/lib/gcc/x86_64-w64-mingw32/4.6/libgcc_s_sjlj-1.dll $HOME/.wine/drive_c/windows/
  - ln -sfn /usr/lib/gcc/x86_64-w64-mingw32/4.6/libgfortran-3.dll   $HOME/.wine/drive_c/windows/
  - ln -sfn /usr/lib/gcc/x86_64-w64-mingw32/4.6/libquadmath-0.dll   $HOME/.wine/drive_c/windows/

install:
  - curl -O http://zlib.net/zlib-1.2.8.tar.gz
  - tar zxvf zlib-1.2.8.tar.gz
  - git clone https://github.com/PacificBiosciences/htslib.git
  - patch -p0 < htslib.patch
  #- curl -O -L https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/pthreads/pthreads-20100604.zip
  #- mkdir -p staging/x86_64-w64-mingw32/include
  #- unzip pthreads-20100604.zip
  #- unzip pthreads-20100604/mingw64/pthreads-w64.zip -d staging
  #- curl -L https://raw.githubusercontent.com/Alexpux/mingw-w64/master/mingw-w64-headers/crt/errno.h -o staging/x86_64-w64-mingw32/include/errno.h

script:
  - make x64
